#!/usr/bin/env python3
"""
AI Agent with Retrieval-Augmented Capabilities
An OpenAI agent that orchestrates retrieval from Qdrant vector database to answer questions about book content.
"""

import os
# Disable OpenAI tracing since it requires native OpenAI API keys and doesn't work with OpenRouter
os.environ['OPENAI_TRACING'] = 'false'

import sys
import logging
import json
from typing import Dict, List, Optional, Any
from datetime import datetime
from dataclasses import dataclass, asdict
import argparse
import time
import uuid
from pydantic import BaseModel
from agents import OpenAIChatCompletionsModel
from openai import AsyncOpenAI
import openai

# Additional OpenAI configuration to disable tracing
openai.tracing = False



# Import required libraries
try:
    from agents import Agent, Runner, function_tool
    import cohere
    from qdrant_client import QdrantClient
    from dotenv import load_dotenv
except ImportError as e:
    print(f"Missing required dependency: {e}")
    print("Please install required dependencies using: pip install -r requirements.txt")
    print("Also install: pip install openai-agents")
    sys.exit(1)

# Load environment variables
load_dotenv()

# Configure OpenAI for the Agents SDK with OpenRouter as third-party provider
# Check for OpenRouter API key first, fall back to OPEN_API_KEY
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPEN_API_KEY_VALUE = os.getenv('OPEN_API_KEY', '')

if not OPENROUTER_API_KEY and not OPEN_API_KEY_VALUE:
    print("[ERROR] Either OPENROUTER_API_KEY or OPEN_API_KEY environment variable is required for the OpenAI Agents SDK")
    sys.exit(1)

# Use OpenRouter API key if available, otherwise fall back to OpenAI API key
api_key_to_use = OPENROUTER_API_KEY if OPENROUTER_API_KEY else OPEN_API_KEY_VALUE

# Set environment variable for compatibility if using OpenRouter
if OPENROUTER_API_KEY:
    os.environ['OPENAI_API_KEY'] = OPENROUTER_API_KEY
else:
    os.environ['OPENAI_API_KEY'] = OPEN_API_KEY_VALUE

openai.api_key = api_key_to_use

# Get model from environment variable, default to the free OpenRouter model
MODEL_NAME = os.getenv('AGENT_MODEL', 'mistralai/devstral-2512:free').lower()

# If using OpenRouter, adjust model name format if needed
# OpenRouter uses different model identifiers than OpenAI
if OPENROUTER_API_KEY:
    # For OpenRouter, we'll use the model specified or default to a compatible one
    # Note: OpenRouter model names might differ from OpenAI's, adjust as needed
    if MODEL_NAME == 'gpt-4o':
        model_name = 'openai/gpt-4o'
    elif MODEL_NAME == 'gpt-4':
        model_name = 'openai/gpt-4'
    else:
        # Use the model as specified, which should already be in OpenRouter format
        model_name = MODEL_NAME
else:
    model_name = MODEL_NAME

# For the agents SDK operations with OpenRouter
Client = AsyncOpenAI(
    api_key=api_key_to_use,
    base_url="https://openrouter.ai/api/v1"  # Use OpenRouter's API endpoint
)

Model = OpenAIChatCompletionsModel(
    openai_client=Client,
    model=model_name  # Use configured model
)

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


# Define Pydantic models for structured outputs
class AgentResponse(BaseModel):
    """Final response generated by the agent based on retrieved content"""
    response: str  # The agent's answer to the user
    sources: List[Dict]  # List of source information used
    confidence: float  # Confidence level in the response (0.0-1.0)
    query: str  # The original user query
    retrieved_chunks: List[Dict]  # The raw retrieved chunks used for the response


class Result(BaseModel):
    """Individual search result from the retrieval tool"""
    chunk_id: str  # Unique identifier for the content chunk
    similarity_score: float  # Similarity score (0.0-1.0)
    content: str  # The retrieved content text
    source_url: str  # Source URL of the content
    document_title: str  # Title of the source document
    chunk_index: int  # Position of the chunk in the original document


class RetrievalToolResponse(BaseModel):
    """Output from the retrieval tool containing relevant content"""
    results: List[Result]  # List of Result objects
    query: str  # The original query
    total_results: int  # Total number of results found
    search_performed: bool  # Boolean indicating if search was executed


# Custom exceptions
class RetrievalError(Exception):
    """Custom exception for retrieval-related errors"""
    pass


class QdrantConnectionError(RetrievalError):
    """Exception for Qdrant connection failures"""
    pass


class APIRateLimitError(RetrievalError):
    """Exception for API rate limit exceeded"""
    pass


def handle_retrieval_error(error: Exception, context: str = "") -> Dict[str, Any]:
    """Handle retrieval errors and return appropriate response"""
    error_msg = str(error)
    logger.error(f"Retrieval error in {context}: {error_msg}")

    if "429" in error_msg or "rate limit" in error_msg.lower():
        return {
            "error": "rate_limit_exceeded",
            "message": "API rate limit exceeded, please try again later"
        }
    elif "401" in error_msg or "Unauthorized" in error_msg:
        return {
            "error": "authentication_failed",
            "message": "Authentication failed. Please check your API keys."
        }
    elif "connection" in error_msg.lower() or "timeout" in error_msg.lower():
        return {
            "error": "connection_failed",
            "message": "Unable to connect to the retrieval service"
        }
    else:
        return {
            "error": "retrieval_error",
            "message": f"An error occurred during retrieval: {error_msg}"
        }


class QdrantConnector:
    """Implements Qdrant connector class to establish connection and validate collection"""

    def __init__(self, config: dict):
        self.config = config
        self.client = QdrantClient(
            url=config['qdrant_url'],
            api_key=config['qdrant_api_key']
        )
        self.collection_name = config['qdrant_collection_name']

    def validate_connection(self) -> bool:
        """Validate Qdrant connection and collection availability"""
        try:
            # Try to get collection info to verify connection
            collection_info = self.client.get_collection(self.collection_name)
            logger.info(f"Successfully connected to Qdrant collection: {self.collection_name}")
            logger.info(f"Collection vector size: {collection_info.config.params.vectors.size}")
            return True
        except Exception as e:
            logger.error(f"Failed to connect to Qdrant: {e}")
            return False

    def get_vector_size(self) -> Optional[int]:
        """Get the vector size of the collection"""
        try:
            collection_info = self.client.get_collection(self.collection_name)
            return collection_info.config.params.vectors.size
        except Exception as e:
            logger.error(f"Failed to get vector size: {e}")
            return None

    def search_similar(self, query_embedding: List[float], top_k: int = 5, threshold: float = 0.5) -> List[Dict]:
        """Perform similarity search in Qdrant to retrieve top-k results"""
        try:
            # Perform search with score threshold
            search_results = self.client.search(
                collection_name=self.collection_name,
                query_vector=query_embedding,
                limit=top_k,
                score_threshold=threshold  # Add threshold filtering
            )

            # Format results according to the original storage module's approach
            formatted_results = []
            for hit in search_results:
                result = {
                    "chunk_id": hit.payload.get("chunk_id", ""),
                    "similarity_score": hit.score,
                    "content": hit.payload.get("content", ""),  # This field may be empty if not stored
                    "source_url": hit.payload.get("source_url", ""),
                    "document_title": hit.payload.get("document_title", ""),
                    "chunk_index": hit.payload.get("chunk_index", 0)
                }
                formatted_results.append(result)

            logger.info(f"Search returned {len(formatted_results)} results")
            return formatted_results
        except Exception as e:
            logger.error(f"Error performing similarity search: {e}")
            return []


class QueryEmbedder:
    """Implements query embedding generation using Cohere API"""

    def __init__(self, api_key: str, model: str = "embed-multilingual-v2.0"):
        """
        Initialize the query embedder
        Uses embed-multilingual-v2.0 which produces 1024-dimensional vectors to match existing embeddings
        """
        self.client = cohere.Client(api_key)
        self.model = model

    def embed_query(self, query_text: str) -> Optional[List[float]]:
        """
        Generate embedding for a query string
        Uses 'search_query' input type for better retrieval performance
        """
        try:
            response = self.client.embed(
                texts=[query_text],
                model=self.model,
                input_type="search_query"  # Appropriate for search queries
            )

            if response.embeddings and len(response.embeddings) > 0:
                embedding = response.embeddings[0]
                logger.debug(f"Generated query embedding with {len(embedding)} dimensions")
                return embedding
            else:
                logger.error("No embeddings returned from Cohere API for query")
                return None

        except Exception as e:
            error_msg = str(e)
            if "401" in error_msg or "Unauthorized" in error_msg:
                logger.error(f"Authentication error with Cohere API (check your API key): {e}")
            else:
                logger.error(f"Error when generating query embedding: {e}")
            return None


def retrieve_content_wrapper(query: str, top_k: int = 5, threshold: float = 0.5) -> Dict[str, Any]:
    """
    Wrapper function for existing retrieval pipeline.
    Retrieve relevant content chunks from Qdrant based on the input query.

    Args:
        query: The search query to find relevant content
        top_k: Number of top results to return. Defaults to 5.
        threshold: Minimum similarity threshold. Defaults to 0.5.

    Returns:
        Dictionary containing search results with content and metadata
    """
    # Validate inputs (redundant validation for direct calls)
    if not query or not isinstance(query, str) or len(query.strip()) == 0:
        return {
            "error": "invalid_query",
            "message": "Query cannot be empty",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }

    if not 1 <= top_k <= 20:
        return {
            "error": "invalid_parameter",
            "message": "top_k must be between 1 and 20",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }

    if not 0.0 <= threshold <= 1.0:
        return {
            "error": "invalid_parameter",
            "message": "threshold must be between 0.0 and 1.0",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }

    try:
        # Load configuration
        config = {
            'cohere_api_key': os.getenv('COHERE_API_KEY'),
            'qdrant_url': os.getenv('QDRANT_URL'),
            'qdrant_api_key': os.getenv('QDRANT_API_KEY'),
            'qdrant_collection_name': os.getenv('QDRANT_COLLECTION_NAME', 'document_embeddings'),
        }

        # Validate required environment variables
        required_vars = ['cohere_api_key', 'qdrant_url', 'qdrant_api_key']
        missing_vars = [var for var in required_vars if not config[var]]

        if missing_vars:
            return {
                "error": "missing_configuration",
                "message": f"Missing required environment variables: {', '.join(missing_vars)}",
                "results": [],
                "query": query,
                "total_results": 0,
                "search_performed": False
            }

        # Create embedder and connector
        embedder = QueryEmbedder(config['cohere_api_key'])
        connector = QdrantConnector(config)

        # Validate connection
        if not connector.validate_connection():
            return {
                "error": "connection_failed",
                "message": "Failed to connect to Qdrant database",
                "results": [],
                "query": query,
                "total_results": 0,
                "search_performed": False
            }

        # Generate embedding for the query
        query_embedding = embedder.embed_query(query)
        if not query_embedding:
            return {
                "error": "embedding_generation_failed",
                "message": "Failed to generate embedding for query",
                "results": [],
                "query": query,
                "total_results": 0,
                "search_performed": True
            }

        # Perform similarity search
        search_results = connector.search_similar(query_embedding, top_k, threshold)

        # Apply threshold filtering to ensure results meet minimum similarity
        filtered_results = [result for result in search_results if result.get('similarity_score', 0) >= threshold]

        # Sort results by similarity score in descending order
        filtered_results.sort(key=lambda x: x.get('similarity_score', 0), reverse=True)

        return {
            "results": filtered_results,
            "query": query,
            "total_results": len(filtered_results),
            "search_performed": True
        }

    except APIRateLimitError as e:
        # Special handling for rate limit errors
        logger.warning(f"API rate limit exceeded: {e}")
        return {
            "error": "rate_limit_exceeded",
            "message": "API rate limit exceeded, please try again later",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": True
        }
    except QdrantConnectionError as e:
        # Special handling for Qdrant connection errors
        logger.error(f"Qdrant connection error: {e}")
        return {
            "error": "connection_failed",
            "message": "Failed to connect to Qdrant database",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }
    except Exception as e:
        # General error handling
        return handle_retrieval_error(e, "retrieve_content_wrapper")


# Define the retrieval tool using the OpenAI Agents SDK function_tool decorator
@function_tool
def retrieve_content(query: str, top_k: int = 5, threshold: float = 0.5) -> dict:
    """
    Retrieve relevant content chunks from Qdrant based on the input query.

    Args:
        query (str): The search query to find relevant content
        top_k (int, optional): Number of top results to return. Defaults to 5.
        threshold (float, optional): Minimum similarity threshold. Defaults to 0.5.

    Returns:
        dict: Dictionary containing search results with content and metadata
    """
    # Input validation
    if not query or not isinstance(query, str) or len(query.strip()) == 0:
        return {
            "error": "invalid_query",
            "message": "Query cannot be empty",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }

    if not isinstance(top_k, int) or top_k < 1 or top_k > 20:
        return {
            "error": "invalid_parameter",
            "message": "top_k must be an integer between 1 and 20",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }

    if not isinstance(threshold, (int, float)) or threshold < 0.0 or threshold > 1.0:
        return {
            "error": "invalid_parameter",
            "message": "threshold must be a number between 0.0 and 1.0",
            "results": [],
            "query": query,
            "total_results": 0,
            "search_performed": False
        }

    return retrieve_content_wrapper(query, top_k, threshold)


# Create the main agent using the OpenAI Agents SDK
def create_agent_with_tools():
    """Create an OpenAI agent with the retrieval tool registered"""
    try:
        # Define the agent with the retrieval tool
        agent = Agent(
            name="RAG Book Assistant",
            instructions="You are an AI assistant that helps users with questions about the Physical AI & Humanoid Robotics book. "
                        "Use the retrieve_content tool to find relevant information from the book content before answering questions. "
                        "Always base your answers on the retrieved content and cite sources when possible. "
                        "If no relevant content is found, acknowledge this and suggest rephrasing the question.",
            tools=[retrieve_content],
            model=Model  # Use the configured model with OpenRouter
        )

        return agent

    except Exception as e:
        logger.error(f"Error creating agent with tools: {e}")
        raise


def process_user_query_with_agents_sdk(query: str) -> str:
    """Process user query using the OpenAI Agents SDK and return formatted response"""
    try:
        # Create the agent with OpenRouter configuration
        agent = create_agent_with_tools()

        # Run the agent with the query using the configured model
        result = Runner.run_sync(agent, query)

        # Return the agent's response
        return result.final_output

    except Exception as e:
        logger.error(f"Error processing user query with Agents SDK: {e}")
        return "Sorry, I encountered an error while processing your request. Please try again."


def run_conversation_loop():
    """Create conversation loop with context management for the agent using Agents SDK"""
    # Determine which provider is being used
    if os.getenv('OPENROUTER_API_KEY'):
        print("[START] Starting AI Agent with Retrieval-Augmented Capabilities (Agents SDK with OpenRouter)")
        print(f"Provider: OpenRouter, Model: {os.getenv('AGENT_MODEL', 'gpt-4o')}")
    else:
        print("[START] Starting AI Agent with Retrieval-Augmented Capabilities (Agents SDK with OpenAI)")
        print(f"Provider: OpenAI, Model: {os.getenv('AGENT_MODEL', 'gpt-4o')}")

    print("You can ask questions about the Physical AI & Humanoid Robotics book content.")
    print("Type 'quit', 'exit', or 'q' to stop the conversation.\n")

    # Initialize the agent
    try:
        agent = create_agent_with_tools()
        print("[OK] Agent initialized with retrieval tools\n")
    except Exception as e:
        print(f"[ERROR] Error initializing agent: {e}")
        print("Please check your environment variables and API keys.")
        return

    # Conversation loop
    while True:
        try:
            user_input = input("\n[USER] You: ").strip()

            if user_input.lower() in ['quit', 'exit', 'q']:
                print(f"\n[EXIT] Goodbye!")
                break

            if not user_input:
                continue

            # Process the user input with the agent using the Agents SDK
            result = Runner.run_sync(agent, user_input)
            response = result.final_output
            print(f"[AGENT] Agent: {response}")

        except KeyboardInterrupt:
            print(f"\n\n[EXIT] Goodbye!")
            break
        except Exception as e:
            print(f"\n[ERROR] Error processing query: {e}")
            continue


def main():
    """Main function to run the AI agent with CLI support using Agents SDK"""
    # Parse command line arguments
    parser = create_cli_parser()
    args = parser.parse_args()

    # Set logging level based on verbose flag
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Check that required environment variables are set
    # If using OpenRouter, we need OPENROUTER_API_KEY; otherwise OPEN_API_KEY
    if args.provider == 'openrouter' or (not args.provider and os.getenv('OPENROUTER_API_KEY')):
        required_vars = ['OPENROUTER_API_KEY', 'COHERE_API_KEY', 'QDRANT_URL', 'QDRANT_API_KEY']
    else:
        required_vars = ['OPEN_API_KEY', 'COHERE_API_KEY', 'QDRANT_URL', 'QDRANT_API_KEY']

    missing_vars = [var for var in required_vars if not os.getenv(var)]

    if missing_vars:
        print(f"[ERROR] Missing required environment variables: {', '.join(missing_vars)}")
        print("Please set these variables in your .env file or environment.")
        return

    # If test mode is enabled, run tests
    if args.test_mode:
        print("[TEST] Running in test mode...")
        test_agents_sdk_functionality()
        return

    # Run the conversation loop
    run_conversation_loop()


def test_agents_sdk_functionality():
    """Test function to validate OpenAI Agents SDK functionality with OpenRouter"""
    print("Testing OpenAI Agents SDK functionality with OpenRouter...")

    # Show which provider is being used
    if os.getenv('OPENROUTER_API_KEY'):
        print(f"Using OpenRouter with model: {os.getenv('AGENT_MODEL', 'gpt-4o')}")
    else:
        print(f"Using OpenAI with model: {os.getenv('AGENT_MODEL', 'gpt-4o')}")

    try:
        # Create the agent with OpenRouter configuration
        agent = create_agent_with_tools()
        print("[OK] Agent created successfully with OpenRouter configuration")

        # Test with a sample query
        test_query = "What are the fundamentals of ROS 2?"
        print(f"\nTesting query: {test_query}")

        result = Runner.run_sync(agent, test_query)
        print(f"Response: {result.final_output[:200]}...")

        print("\n[SUCCESS] OpenAI Agents SDK test with OpenRouter completed successfully")

    except Exception as e:
        print(f"\n[ERROR] OpenAI Agents SDK test with OpenRouter failed: {e}")


def create_cli_parser():
    """Create command-line argument parser"""
    parser = argparse.ArgumentParser(
        description="AI Agent with Retrieval-Augmented Capabilities (Agents SDK with OpenRouter support)"
    )
    parser.add_argument(
        '--top-k',
        type=int,
        default=3,
        help='Number of results to retrieve (default: 3)'
    )
    parser.add_argument(
        '--threshold',
        type=float,
        default=0.3,
        help='Similarity threshold for results (default: 0.3)'
    )
    parser.add_argument(
        '--test-mode',
        action='store_true',
        help='Run in test mode with predefined queries'
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Enable verbose logging'
    )
    parser.add_argument(
        '--provider',
        type=str,
        choices=['openrouter', 'openai'],
        help='Specify the provider to use (default: openrouter if OPENROUTER_API_KEY is set, otherwise openai)'
    )

    return parser


if __name__ == "__main__":
    main()