// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Default autogenerated sidebar (optional)
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Custom sidebar for the Physical AI Book
  physicalAISidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'], // Make sure intro.md exists
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: Fundamentals of Physical AI',
      items: [
        {
          type: 'category',
          label: 'Chapter 1.1: Introduction to Physical AI',
          items: [
            'module-1/chapter-1/lesson-1',
            'module-1/chapter-1/lesson-2',
            'module-1/chapter-1/lesson-3',
            'module-1/chapter-1/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 1.2: Sensing the Physical World',
          items: [
            'module-1/chapter-2/lesson-1',
            'module-1/chapter-2/lesson-2',
            'module-1/chapter-2/lesson-3',
            'module-1/chapter-2/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 1.3: Actuation and Control',
          items: [
            'module-1/chapter-3/lesson-1',
            'module-1/chapter-3/lesson-2',
            'module-1/chapter-3/lesson-3',
            'module-1/chapter-3/lesson-4'
          ],
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Perception and Reasoning in Physical Systems',
      items: [
        {
          type: 'category',
          label: 'Chapter 2.1: Computer Vision for Physical AI',
          items: [
            'module-2/chapter-1/lesson-1',
            'module-2/chapter-1/lesson-2',
            'module-2/chapter-1/lesson-3',
            'module-2/chapter-1/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2.2: Spatial Reasoning and Navigation',
          items: [
            'module-2/chapter-2/lesson-1',
            'module-2/chapter-2/lesson-2',
            'module-2/chapter-2/lesson-3',
            'module-2/chapter-2/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2.3: Decision Making and Planning',
          items: [
            'module-2/chapter-3/lesson-1',
            'module-2/chapter-3/lesson-2',
            'module-2/chapter-3/lesson-3',
            'module-2/chapter-3/lesson-4'
          ],
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: Advanced Physical AI Applications',
      items: [
        {
          type: 'category',
          label: 'Chapter 3.1: Human-Robot Interaction',
          items: [
            'module-3/chapter-1/lesson-1',
            'module-3/chapter-1/lesson-2',
            'module-3/chapter-1/lesson-3',
            'module-3/chapter-1/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3.2: Edge AI and Real-time Processing',
          items: [
            'module-3/chapter-2/lesson-1',
            'module-3/chapter-2/lesson-2',
            'module-3/chapter-2/lesson-3',
            'module-3/chapter-2/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3.3: Integration and Deployment',
          items: [
            'module-3/chapter-3/lesson-1',
            'module-3/chapter-3/lesson-2',
            'module-3/chapter-3/lesson-3',
            'module-3/chapter-3/lesson-4'
          ],
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) Models',
      items: [
        {
          type: 'category',
          label: 'Chapter 4.1: VLA Fundamentals',
          items: [
            'module-4/chapter-1/lesson-1',
            'module-4/chapter-1/lesson-2',
            'module-4/chapter-1/lesson-3',
            'module-4/chapter-1/lesson-4'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4.2: Advanced VLA Applications',
          items: [
            'module-4/chapter-2/lesson-1',
            'module-4/chapter-2/lesson-2'
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4.3: VLA Evaluation and Ethics',
          items: [
            'module-4/chapter-3/lesson-1',
            'module-4/chapter-3/lesson-2'
          ],
        },
      ],
      collapsed: false,
    },
  ],
};

module.exports = sidebars;
